# Generated by Django 3.0.7 on 2020-07-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmpinregister',
            name='balance',
            field=models.CharField(default='100000', max_length=50),
        ),
    ]
